name: Deploy to Google App Engine - Dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy_dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Env Replace
        run: |
          npm run env:replace
        env:
          NODE_ENV: dev
          INFISICAL_CLIENT_ID: ${{ secrets.INFISICAL_CLIENT_ID }}
          INFISICAL_CLIENT_SECRET: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          INFISICAL_WORKSPACE_SLUG: ${{ secrets.INFISICAL_WORKSPACE_SLUG }}

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.SECRETJSON_DEV }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Deploy to Google App Engine
        run: |
          gcloud app deploy --appyaml=app.yaml --quiet -v=live --no-cache
