name: Deploy to Google App Engine - Prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_prod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Env Replace
        run: |
          npx tsx ./scripts/env-replace
        env:
          NODE_ENV: production
          INFISICAL_CLIENT_ID: ${{ secrets.INFISICAL_CLIENT_ID }}
          INFISICAL_CLIENT_SECRET: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          INFISICAL_WORKSPACE_SLUG: ${{ secrets.INFISICAL_WORKSPACE_SLUG }}

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.SECRETJSON_PROD }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Deploy to Google App Engine
        run: |
          gcloud app deploy --appyaml=app.yaml --quiet -v=live --no-cache
