name: Deploy to Google App Engine - Prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_prod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Load Secrets in Env
        run: |
          npx tsx ./scripts/load-secrets
        env:
          NODE_ENV: production
          INFISICAL_CLIENT_ID: ${{ secrets.INFISICAL_CLIENT_ID }}
          INFISICAL_CLIENT_SECRET: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          INFISICAL_PROJECT_ID: ${{ secrets.INFISICAL_PROJECT_ID }}

      - name: Env Replace in app.yaml
        run: |
          npx tsx ./scripts/env-replace
        env:
          NODE_ENV: production

      - name: Start Xata Migration from dev to main
        run: |
          echo ${{ github.event.head_commit.message }}
          if [[ ${{ github.event.head_commit.message }} =~ '^Merge pull request #\d+ from .*\/dev\b' ]]; then
            npx tsx ./scripts/migraiton-start dev main
          fi

      # - id: "auth"
      #   uses: "google-github-actions/auth@v2"
      #   with:
      #     credentials_json: "${{ secrets.SECRETJSON_PROD }}"

      # - name: Set up Cloud SDK
      #   uses: "google-github-actions/setup-gcloud@v2"

      # - name: Deploy to Google App Engine
      #   run: |
      #     gcloud app deploy --appyaml=app.yaml --quiet -v=live --no-cache

      - name: Complete Xata Migration from dev to main
        run: |
          if [[ ${{ github.event.head_commit.message }} =~ '^Merge pull request #\d+ from .*\/dev\b' ]]; then
            npx tsx ./scripts/migraiton-complete dev main
          fi
